language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0

notifications:
  email:
    on_success: change
    on_failure: always

script: SPEC_ALL=true bundle exec rspec spec
before_install:
 - gem update bundler
after_success:
  - bundle exec codeclimate-test-reporter
